name: docfx

# Trigger the action on push to main
on:
  push:
    branches:
      - main
  workflow_dispatch:

# The reusable workflow's token cannot exceed these.
permissions:
  actions: read
  pages: write
  id-token: write

jobs:
  publish-docs:
    uses: RushuiGuan/devops/.github/workflows/github-page.yml@v1
